### ISSUE TITLE
Chart Range: Gets destroyed on click when no timestamp is present

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#100]
If no timestamp is present we should not destroy the range. Filter out the click and ignore it if no timestamp is set

**Comment by renepanzar** [comment]
Any info on when this will be addressed?

**Comment by lukasholzer** [comment]
> Any info on when this will be addressed?

Currently working on this bug.
The problem with fixing this bug is that we have to support this behaviour – in the case that a range and a timestamp can be used together this is a valid behaviour because with a click the range it gets destroyed to create a timestamp.

All our logic (event listeners and handling) is based on that there can exist a timestamp and a range so it makes it hard to fix this bug. Will require some rewrites of the core functionality of the selection area.

**Comment by renepanzar** [comment]
@lukasholzer, thanks for the heads-up!
