### ISSUE TITLE
[Filter field]: Chaining of selected nodes to construct custom key:value pairs

### ISSUE THREAD

**Issue by airime** [dynatrace-oss/barista#1113]
# Feature Request

Allow dropdown selection of various filter options in succession, in order to compose a user-defined key:value pair.

## Summary

The `DtFilterField` component is currently implemented in a way that the first node you selected in the dropdown is used as the key, and after completing the filter the last node you selected is chosen as the value. This request is for adding a configuration that allows composing all the selected nodes (except for the last selected one) together in the key, and the last selected one as the value.

## Feature Description

The use case to cover is to go through a chain of selections and end up with a composed key:value pair of all the choices made by the user, where only the last choice the user made is the value and the rest are concatenated in the key. It is important that the user choices are made in different steps, and this feature is needed for a coming release.

Here are some screenshots of how it could look:

![Screenshot 2020-06-04 at 18 35 49](https://user-images.githubusercontent.com/6683824/83786021-6d745d00-a692-11ea-8449-753ff70e304f.png)
![Screenshot 2020-06-04 at 18 36 16](https://user-images.githubusercontent.com/6683824/83786043-78c78880-a692-11ea-891b-4ff04f97816e.png)
![Screenshot 2020-06-04 at 18 36 28](https://user-images.githubusercontent.com/6683824/83786064-7f560000-a692-11ea-9944-255fb1a7bcd7.png)
![Screenshot 2020-06-04 at 18 36 37](https://user-images.githubusercontent.com/6683824/83786072-8250f080-a692-11ea-8cdb-9ab5acccb625.png)

In order to achieve it, one way could be to add a new `concatenate` keyword that allows defining a separating character between nodes, so that, when several nested autocomplete options are configured, the component knows that they should be added together and the user knows all the path of options that was chosen with one look.

**Comment by tomheller** [comment]
Hi @airime ! Thank you for opening up this feature request. 

I guess if we are talking about customizing the `key` displayed in the filter-field tag we should discuss a more generic approach that lets the consumer customize this based on a custom function that is provided. 

__Scope__ 
Do you know if these customizations need to happen on a filter-field or filter basis?
Is there anything besides the `key` that should be customizable for this use case (like the separator character between the key and the value)? 

__Possible solution__
We already have an internal function that creates the `key: value` and metadata pairings for the `filter-field tag` ([filter-field-utils.ts#L291-L334](https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/filter-field/src/filter-field-util.ts#L291-L334)). As we do not want to expose the whole function to the consumer (this could cause a lot of problems  in the data consistency and how we further process the data in the filter field), we were thinking of a consumer function that gets a filterValues[] and will return the string that should be used to display.

**Comment by thomaspink** [comment]
Hi @airime. As @tomheller said, thank you for this PR.

I got currently 2 solutions in mind. The second one more flexible than the first one:

**1.**
The filter tag (which is responsible for displaying on filter) right now takes an instance in the form of `_DtFilterFieldTagData` which holds all the necessary information for displaying and interacting with a filter. I would suggest to remove the properties `key`, `value` and `separator`and move it into a`DtFilterFieldTagViewValues` object which the consumer can override (maybe via a construction function he can provide). This view-data object can then be again a part of the whole `_DtFilterFieldTagData` object and then be passed down to the tag.

```ts
export class DtFilterFieldTagViewValues {
  constructor(
    public key: string | null,
    public value: string | null,
    public separator: string | null,
  ) {}
}

export class _DtFilterFieldTagData {
  constructor(
    public viewValues: DtFilterFieldTagViewValues,
    public isFreeText: boolean,
    public filterValues: _DtFilterValue[],
    public editable: boolean = true,
    public deletable: boolean = true,
  ) {}
}

// This function can be provided by the consumer
export type createDtFilterFieldTagViewValues = 
  (filter: _DtFilterValue[]) => DtFilterFieldTagViewValues;
```

The function @tomheller has mentioned can the call the `createDtFilterFieldTagViewValues` if one is provided and pluck in the view values into the tag data.


**2.**
We can give more flexibility to the consumer when we change the logic to be template driven. So the consumer can provide his custom template for the tags which we then render by passing the values of the filter (`_DtFilterValue[]`) via the `$implicit` context.

**Conclusion**
This first solution is more konservative than the second one and just lets you override the `key`, `value` and `separator` which is probable more suitable because it might not be great for UI if the consumer can completely override on how tags are displayed like in the second solution. The second one basically give the consumer the full power and the tag can change completely (even in a way that it might not work with our UX guidelines).

Hope this helps. If you have a different idea in mind I am looking forward to hear it. 

:)

**Comment by kaikcreator** [comment]
Thanks for your suggestions @thomaspink!

Regarding the second approach, I understand that this one depends on an epic/story in order to change the logic to be template driven, right? Is there any time estimation / roadmap for this change?

**Comment by tomheller** [comment]
I would still prefer the first approach, as it is less invasive to the filter-field itself. I have added the _requirement_ also to the list of requirements for the new filter-field. 
@airime would this be something you would be willing to contribute to the library? We would offer assistance, if you need any help during the contribution process.
