### ISSUE TITLE
Add directive for text to confirmation dialog to make styling easier

### ISSUE THREAD

**Issue by SirTroyer** [dynatrace-oss/barista#1148]
# Feature Request
## Summary

Add directive for text in a confirmation dialog to make styling easier when `dt-confirmation-dialog-state` also consists of `dt-confirmation-dialog-actions`. In which case the user would have to style the text himself to introduce a little margin between text and buttons.

## Feature Description

Currently, there is a directive for actions in a `dt-confirmation-dialog-state` which is called `dt-confirmation-dialog-actions`. Text can be inserted anywhere in the `dt-confirmation-dialog-state` 
but if a user wants to use text and buttons at the same time in the confirmation dialog, which is often the case, the user has to style the text himself to create a little margin between text and buttons.
It would be cool for the text to have its own directive that will style it.

![confirmation-dialog](https://user-images.githubusercontent.com/61140594/84142836-ceff4780-aa55-11ea-9283-bc19e6a6f177.png)

**Comment by tomheller** [comment]
Hi @SirTroyer!

Instead of adding an additional directive for the text, as this can be styled however consumers want, as long as they create their own wrapping element, I would opt to add styling to the class applied to the `dt-confirmation-dialog-actions` directive and add the spacing there. 

The default `ng-content` should still work the same without requiring an extra wrapping element for the text itself. 

Would this also work for you?
