### ISSUE TITLE
Filter field: validation error is displayed while field is dirty

### ISSUE THREAD

**Issue by pawel-bugalski-dynatrace** [dynatrace-oss/barista#1180]
# Bug Report

## Expected Behavior

Error message should be displayed only once field is submitted.

## Current Behavior

Error message is displayed for a split second while field is dirty.

## Attachments

Example reproduction of an issue:
[barista filter - blinking error.mov.zip](https://github.com/dynatrace-oss/barista/files/4811858/barista.filter.-.blinking.error.mov.zip)
This reproduction was produced with verification example: https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleFilterFieldValidator/?file=src%2Ffilter-field%2Ffilter-field-validator-example%2Ffilter-field-validator-example.ts
but using following data source:
```
export class DtExampleFilterFieldValidator {
  private DATA = {
    autocomplete: [
      {
        name: 'content',
        suggestions: [], validators: [
          { validatorFn: Validators.required, error: 'Content can not be empty.' },
        ],
      },
    ],
  };
  _dataSource = new DtFilterFieldDefaultDataSource(this.DATA);
}
```

**Comment by ffriedl89** [comment]
Thx @pawel-bugalski-dynatrace for reporting this issue. 
It is actually intentional to display the error message once the field is dirty. 

We show validation errors once the field is dirty and invalid - which means that the user interacted with it and there is an error

E.g. The user started typing in a required field (no error) - but then the user deletes the value (show error - since it was interacted with and its invalid due to the required validation) 

But the flash of the error message once the user types the first character is a bug.
