### ISSUE TITLE
[Filter Field]: Multiselect option

### ISSUE THREAD

**Issue by kaikcreator** [dynatrace-oss/barista#1206]
# Feature Request

## Summary

Add multiselect option into filter component

## Feature Description

Right now, the user cannot select several values for the same filter type in a grouped way. A multiselect feature will allow the user to achieve that goal.

Probably, the best approach would be creating a new panel for multiselection, following the same approach used with the range filter type. This panel could display a scrollable list with all the available suggestions, a checkbox in order to select some of the values, and an Apply button (so changes can be dismissed otherwise).

 See attached screenshots. 

Extra data:
* The multiselect panel should have it's own internal state (so it can "cancel" not-yet-applied filters).
* A click outside panel would cancel the changes
* A click on a already applied multiselect filter would open again the panel, in order to change selection
* The multiselect panel should be keyboard compliant

## Attachments

Start typing the filter key, as usual
<img width="813" alt="multiselect_0" src="https://user-images.githubusercontent.com/7058118/85741697-eea79880-b702-11ea-887b-4cb6cd47cba1.png">

If it is a multiselect filter, then display a panel with the available options
<img width="857" alt="multiselect_1" src="https://user-images.githubusercontent.com/7058118/85741706-f109f280-b702-11ea-8278-9435201f3b7a.png">

When the user updates the checkboxes selection, the text in the chip is also updated
<img width="921" alt="multiselect_2" src="https://user-images.githubusercontent.com/7058118/85741716-f2d3b600-b702-11ea-9e22-e33070605d89.png">
<img width="921" alt="multiselect_3" src="https://user-images.githubusercontent.com/7058118/85741722-f36c4c80-b702-11ea-82f7-333713dd435a.png">

Once the filter is applied, the chip reflects all the applied values following a comma-separated approach
<img width="872" alt="multiselect_4" src="https://user-images.githubusercontent.com/7058118/85741723-f404e300-b702-11ea-94c6-8415b294c0cf.png">

The user can go back at any point and click on the chip so the panel is opened again for further interaction
<img width="960" alt="multiselect_5" src="https://user-images.githubusercontent.com/7058118/85741726-f49d7980-b702-11ea-9384-4d25f855aeb5.png">.

**Comment by rowa-audil** [comment]
Hello @kaikcreator,

thank you for proposing this request, we think this is a useful feature for the Filter Field. Would you be willing to contribute that yourself?

**Comment by rowa-audil** [comment]
For the chosen one to create this feature, here is what you will need to proceed.

First, figure out an **API Proposal** that explains how you will build the feature. 
What will you need to achieve that feature and what will change basically. The filter field is not for weak souls so prepare yourself to tackle this with critically thinking confidence.
Some questions come up concerning some edge cases. What happens when no boxes are checked and when lots of boxes are checked.

NOTE: Use our barista checkbox component to implement that feature. We don't like to see style adjustments since the checkbox in your screenshots already looks different from ours.

**Comment by kaikcreator** [comment]
Hi @rowa-audil , yes. Maybe not me, but someone in our team will contribute to this feature, definitely.
We will provide an API asap, but first we need to understand a bit better how the range option is implemented, because we thought we should follow a similar approach. Any suggestion here @tomheller @ffriedl89 ?

**Comment by tomheller** [comment]
@kaikcreator, the filter field is in it's current state not very extendible, that's why also the range is very interwoven with the filter field in general. There are a lot of things that determine what _overlay_ should open up. 
I guess you should follow the approach of the range, but there are a couple of pitfalls, that may need to be taken into account. 

## Datatype
The range defines it's own data-type within the datasource definitions of the filterfield (including a couple of helper functions, that help identify if the node is a range node or not and also compare nodes). You will definitely need similar functions like that. 

https://github.com/dynatrace-oss/barista/blob/f8a00b33ec830fcf8db65ce16b4809c61b09115b/libs/barista-components/filter-field/src/types.ts#L83-L151

https://github.com/dynatrace-oss/barista/blob/f8a00b33ec830fcf8db65ce16b4809c61b09115b/libs/barista-components/filter-field/src/filter-field-util.ts#L491-L502

## Visual representation
The range implements it's own version of the [autocomplete behavior within it's component](https://github.com/dynatrace-oss/barista/tree/master/libs/barista-components/filter-field/src/filter-field-range), and I think this would be definitely a good approach here as well.
The overlay and trigger are always created when the filter-field is created, the _overlays_ are opened programmatically by the filter field. (if the overlay should not be shown, they are disabled on the trigger to prevent them visually appearing).

https://github.com/dynatrace-oss/barista/blob/f8a00b33ec830fcf8db65ce16b4809c61b09115b/libs/barista-components/filter-field/src/filter-field.html#L85-L92

https://github.com/dynatrace-oss/barista/blob/f8a00b33ec830fcf8db65ce16b4809c61b09115b/libs/barista-components/filter-field/src/filter-field.ts#L434-L474

## Dealing with edit mode

The edit mode within the filter field is a little bit tricky in regards to state management, as you need to restore the editing filter as the current filter. You will probably need some edits in this function to do this properly for the mutli-select.

https://github.com/dynatrace-oss/barista/blob/f8a00b33ec830fcf8db65ce16b4809c61b09115b/libs/barista-components/filter-field/src/filter-field.ts#L664-L709

**Comment by kaikcreator** [comment]
Thanks @tomheller, this will definitely help us a lot!!!

**Comment by subarroca** [comment]
Thinking of possible groups, it would be good to adopt autocomplete options and groups

````ts
export interface DtMultiSelectDef<OpGr = unknown, Op = unknown> {
  optionsOrGroups: DtNodeDef<OpGr>[];
}
````

Update `DtNodeFlags` with a new type

````ts
export enum DtNodeFlags {
  None = 0,
  TypeAutocomplete = 1 << 0,
  TypeFreeText = 1 << 1,
  TypeOption = 1 << 2,
  TypeGroup = 1 << 3,
  TypeRange = 1 << 4,
  TypeMultiSelect = 1 << 5,
  RenderTypes = TypeAutocomplete | TypeFreeText | TypeRange | TypeMultiSelect,
  Types = TypeAutocomplete | TypeFreeText | TypeOption | TypeGroup,
}
````

````ts
export function isDtMultiSelectDef<D = unknown>(
  def: DtNodeDef<D> | null,
): def is DtNodeDef<D> & DtMultiSelectDef {
  return isDtNodeDef(def) && !!(def.nodeFlags & DtNodeFlags.TypeMultiSelect);
}
````

## DtFilterFieldMultiSelect ##
### Inputs ###
|Name|Type|Description|
|-|-|-|
|optionsOrGroups|`DtNodeDef<OpGr>[]`| Already selected options|

### Outputs ###
|Name|Emits|Description|
|   opened | `void`| Panel is opened|
|closed|  `void`| Panel is closed|
|  optionsSubmitted | `DtNodeDef<OpGr>[]`| Options selected by the user|

## DtFilterFieldMultiSelectTrigger ##

### Inputs ###
|Name|Type|Description|
|-|-|-|
|dtFilterFieldMultiSelect|`DtFilterFieldMultiSelect`|The filter-field multi select panel to be attached to this trigger.|
|dtFilterFieldMultiSelectDisabled|`boolean`|Whether filter-field multi select panel should be disabled.|

**Comment by subarroca** [comment]
@tomheller I'll start with this next week

**Comment by subarroca** [comment]
For the list of checkboxes I'm thinking of using the ReactiveFormsModule, but I see that we're not using it anywhere on the filter. Is there a reason for that so I should avoid it or am I able to use it? @thomaspink @tomheller

**Comment by tomheller** [comment]
You can use it if you want to, or create your own selectionModel from cdk as @dt-mafe does in his pr about the selectable rows #1052

**Comment by lukasholzer** [comment]
Not on our roadmap.
