### ISSUE TITLE
Sunburst chart text labels cut off

### ISSUE THREAD

**Issue by airime** [dynatrace-oss/barista#1352]
# Bug Report

## Expected Behavior

Text labels of chart should be displayed without cutting.
![Screenshot 2020-07-22 at 19 29 52](https://user-images.githubusercontent.com/6683824/88208759-fe5ac400-cc51-11ea-9091-cd60cb134ce7.png)

## Current Behavior

Text labels can cut off when children are expanded.
![Screenshot 2020-07-22 at 19 25 57](https://user-images.githubusercontent.com/6683824/88208693-e97e3080-cc51-11ea-9260-3185ef7775ca.png)

## Possible Solution

At line:
https://github.com/dynatrace-oss/barista/blob/9645d4bbde772a1dde56351afd4508eea2ddc54d/libs/barista-components/sunburst-chart/src/sunburst-chart.scss#L14
Add overflow: visible;

## Steps to Reproduce

1. Sunburst chart has some sort of width restriction.
2. Open up children in a way that the text labels step outside the container box of the chart.

## Context (Environment)

The sunburst chart was used to show browser navigation data: the types of browsers, with their families, with their versions.

### Used Versions:

- **node**: 12.10.0
- **npm**: 6.11.3
- **typescript**: 3.8.3
- **angular**: 9.1.12
- **@angular/cdk**: 9.2.4
- **@dynatrace/barista-components**: 7.4.0

**Comment by lukasholzer** [comment]
Thank you for reporting this issue @airime do you want to contribute this fix? 

To mention another possible solution would be to ellipsis the text like `AOL Explo...` as I don't know how long these labels can be. Think about some weird long hostnames that can take up to 60 characters I don't think `overflow: visible` would be then that nice. Maybe a max-width that is a little bit longer than the current one and start ellipsing this.

@tomheller  what's your opinion on that?

**Comment by tomheller** [comment]
Neither option is really a good one. `Overflow: visible` would let the text flow out of it's container and therefore would probably be able to flow over other components that are next to it. 

The ellipsis part is also a bit tricky, as it is an svg text element that does not easily follow the default reflowing rules of the box model. 

The most resilient solution would be to have an algorithm figure out where to put the label, as it does not need to be dead center in the segment, or size the whole chart smaller if there are very long labels.
This would also allow us to reduce / avoid label positions like these, which are not very accessible from a contrast perspective.
<img width="137" alt="image" src="https://user-images.githubusercontent.com/6338434/88254741-72c74e80-ccb6-11ea-95b6-e6a3d9c500d6.png">

But an approach like this would be probably fairly complicated. I vaguely remember trying something similar for the radial chart. There we never needed to fully solve that problem, because the legend moved out of the chart completely.
@subarroca as a codeowner of the sunburst chart do you have a take on this?

**Comment by subarroca** [comment]
My approach would be making the chart wider. Right now it's a 1:1 ratio, taking it to 4:3 ratio, for instance, would allow us to move the labels a bit more outside. It's true that this would reduce the size of the chart a bit but I don't think it's critical.
Also, regarding long labels, giving this extra space would reduce the overlap label-slice, and if we add the limitation of n-chars and we cut the labels with a pipe this would do the trick of simulating an ellipsis.

I don't think it's really a pushing issue, I'll be free in 2 or 3 weeks so if you can wait I can take this

**Comment by tomheller** [comment]
Making the chart wider will be a temporary fix, but I do believe that we should strive for a solution that would work even for long labels. It would be fine with me if we adjust the aspect ratio of the chart and add some scripted ellipses into the labels for ones that are very long.

**Comment by lukasholzer** [comment]
Moved to APM-266078
