### ISSUE TITLE
Page not found in section "card layout"

### ISSUE THREAD

**Issue by gabrielprioli** [dynatrace-oss/barista#1368]
Sorry if this shouldn't be a bug report, but I though it was better than Feature request.

# Bug Report

## Expected Behavior

The link "layout pattern" in section https://barista.dynatrace.com/components/card#card-in-use should be valid.

## Current Behavior

Link returns a page not found error.
```

404: NOT_FOUND
Code: NOT_FOUND

NOTE: might be available. Click here to learn how to assign it to a project.
Powered by [Vercel]

```
## Steps to Reproduce

1. Access https://barista.dynatrace.com/components/card#card-in-use
2. Click on the link "layout pattern"

## Attachments

![image](https://user-images.githubusercontent.com/836297/88459715-dcd62400-ce6d-11ea-9079-4eb3f7aa3204.png)

**Comment by tomheller** [comment]
HI @gabrielprioli!

Thank you for reporting this. This can be considered a bug though, this is fine. 
The page that we are linking to here is considered `internal`, so the page should not be found. I'm currently in the process of replacing the link with a correct one, so that it will be picked up by the internal content filter.

**Comment by tomheller** [comment]
The issue has been resolved, the link is now removed as the target page is not inside the public pages set.
