### ISSUE TITLE
Research: Web components & Forms

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1386]
# Feature Request

## Summary

Webcomponents don't play nice with the native form tag. Therefore web component libraries like [shoelace](https://shoelace.style/components/form) or [lion](https://github.com/ing-bank/lion/tree/master/packages/form) use custom form tags to handle the interop between custom form elements and the form.

### Why?

Research what we need in terms of features / requirements and outline why it is necessary. 

### Framework integration
Check integration with frameworks like Angular - how does a custom form control work together with angular forms for instance. Does this change anything for us?  

Document findings and learnings here on the issue.

**Comment by bardosmisi** [comment]
## The problem

If we want to use web component based form elements, the native form will not be compatible with those. Also in order to maintain compatibility with angular, and barista, we have to find the best way of using these web components with them.

## Possible solutions

During the research I have looked at different UI libraries, to see how they got around the problem presented above. There are different solutions with different constraints for the consumer, and for the maintainer.

If we want a form component that is compatible with all the native input elements, and the input components from the fluid elements, we have to maintain the compatibility in the form component itself. This would mean that we have to implement behavior that is already present in the native form element, and also maintain it.

Another option is to place a constraint on the consumer, and restrict them to use specific input elements, that will handle the compatibility with the parent form component.

The first option seems more feasible, because even tho' the implementation will be more complex, the possibility of using native form elements is a big advantage (I think).

## API proposal

```html
<fluid-form>
  <fluid-checkbox
  [disabled]="false"
  [checked]="false"
  value="checkbox"
  name="checkbox"
  >
    Label
  </fluid-checkbox>
  <input name="name" type="text" value="something" />
</fluid-form>
```

### Input
```
// I am not yet entirely sure about this, so feedback is appreciated. Initial form Data that will be set on the form elements.
inputFormData: FormData
```

### Events
```ts
// Event to dispatch on form submit
@onSubmit dispatchSubmit(formData: FormData)
```

### Methods
```ts
// When called the form component will serialize the elements in itself, and return the assembled FormData.
getFormData(): FormData;
```

## Future Plans
- Add an API to extend the compatibility of the form component with additional custom elements.
- Add validation capabilities
- Investigate accessibility implications
- The submit button could come from outside the the component, we could introduce logic to add the submit button if not present.

## Reference
- The POC and the examples of different forms are here: https://github.com/bardosmisi/form-poc

**Comment by lukasholzer** [comment]
We will close this issue as web components are not the way we want to create components in the future this is related to a shift of priorities in the team.
