### ISSUE TITLE
Chart tooltip disappearing when new data arrives.

### ISSUE THREAD

**Issue by TannerGilbert** [dynatrace-oss/barista#1410]
# Bug Report

## Expected Behavior

Chart tooltip should update, when new values are received.

## Current Behavior

Tooltip values are being removed but new values aren't added.

## Steps to Reproduce
* https://stackblitz.com/edit/github-vilm5e?file=src/chart/chart-stream-example/chart-stream-example.html

### Used Versions:

- **typescript**: 3.8.3
- **@angular/cdk**: 9.2.4
- **@dynatrace/barista-components**: 7.6.0

## Attachments
![barista_tooltip_disappearing2](https://user-images.githubusercontent.com/36239763/89014984-a178a100-d316-11ea-9c49-6aa318c1faa0.gif)

![barista_tooltip_disappearing](https://user-images.githubusercontent.com/36239763/89014999-a6d5eb80-d316-11ea-8bff-29be781ea946.gif)

**Comment by tomheller** [comment]
@TannerGilbert Thank you for reporting this. This definitely seems like a bug. 

I already have a guess that we are not getting a new `seriesHover` event from highcharts, and therefor do not update the implicit context of the overlay.

**Comment by tomheller** [comment]
As expected, highcharts does not send a new `tooptipUpdated` event, if the mouse does not move.
If you have a look at the highcharts dynamic chart example [1], if you hover over a data point and do not move the mouse, the tooltip moves with the set datapoint. 

My current approach to solve this, would be to see if we can either:
- Get the hovered series data from highcharts, when the data changes and fake the tooltip data in manually.
- Dispatch a fake mouse event to force highcharts to refire the `tooltipUpdated` event.

[1]: https://www.highcharts.com/demo/live-data

**Comment by tomheller** [comment]
This seems more and more like something that cannot be fixed. At least not in the way highcharts is currently wrapped into the `dt-chart`.

When the series data is being set, the charts update function is called:
https://github.com/dynatrace-oss/barista/blob/24647e8c15b388cd128ba102fe9f6cf1ffbb4620/libs/barista-components/chart/src/chart.ts#L232-L236

In this update function, we need to destroy the current chart object and reinstantiate it again. Highcharts has an update function, although this will not let the consumer update all properties of the series or chart options. This has been leading to problems in the past, which is why we implemented the re-instantiation functionality in 6df1df81f9f935e6185505757893b4a4ba965099.

Before the change, the update function looked like this, where the new series and options were passed to the `Highcharts.update` function.
https://github.com/dynatrace-oss/barista/blob/dd7fa6f35daa06593081a9700c74fe50757f77ef/src/lib/chart/chart.ts#L543-L553


I currently do not see a good way to solve this issue without reintroducing old problems. Any input would be appreciated @ffriedl89 @lukasholzer. 
The same root cause applies to issue #1412.
