### ISSUE TITLE
Chart filtering resets when new data arrives.

### ISSUE THREAD

**Issue by TannerGilbert** [dynatrace-oss/barista#1412]
# Bug Report

## Expected Behavior

Column filtering shouldn't be affected by new data.

## Current Behavior

After data changes all columns are visible again.

## Steps to Reproduce
- https://stackblitz.com/edit/github-vilm5e?file=src/chart/chart-stream-example/chart-stream-example.html

### Used Versions:

- **typescript**: 3.8.3
- **@angular/cdk**: 9.2.4
- **@dynatrace/barista-components**: 7.6.0

## Attachments

![barista_visability_reseting](https://user-images.githubusercontent.com/36239763/89030087-08ef1a80-d330-11ea-8339-f2c7c609f68d.gif)

**Comment by tomheller** [comment]
It seems that highcharts under the hood cannot connect the currently set series with the one newly set one, hence resetting the filter. 
I have a hunch  that it deals with object equality internally, and if we set completely new series data, instead of only updating the `data` property within the series, it will loose that filter. 
Further investigations are probably necessary.
