### ISSUE TITLE
[Filter field / Autocomplete] Virtualized elements change width of overlay when scrolled into view.

### ISSUE THREAD

**Issue by kaikcreator** [dynatrace-oss/barista#1420]
# Bug Report

## Expected Behavior

Filter suggestions panel width should consider max with of their content from the beginning.

## Current Behavior

Right now, the filter suggestions panel width only takes into account the data displayed when expanded, but if some wider content appears on scroll, the width of the panel is adjusted (causing an unsightly "jump" effect).

## Steps to Reproduce

See live code: https://stackblitz.com/edit/github-g3mxzb

1. Click in filter component
2. Select `item` filter key
3. Scroll down suggestions until `some even much longer item` is displayed

**Comment by tomheller** [comment]
Hey @kaikcreator! Thank you for reporting this, this seems like a problem with the virtualization of the items in the autocomplete component.

I will have a look.

**Comment by tomheller** [comment]
I have tracked it down to the usage of the `dt-highlight` in the filter-field options, which wrap all option elements.
https://github.com/dynatrace-oss/barista/blob/a1d28385b74f41762e3b101c0395c5d994e3edae/libs/barista-components/filter-field/src/filter-field.html#L77-L79

The dt-highlight only renders, when it is in viewport, which let's the dropdown grow as you scroll down, because the options only are rendered in the dom when they become visible. 
https://github.com/dynatrace-oss/barista/blob/a1d28385b74f41762e3b101c0395c5d994e3edae/libs/barista-components/highlight/src/highlight.ts#L138-L146
