### ISSUE TITLE
[QuickFilter] Requirements to be Stable

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1451]
# Requirements to make it stable

Currently, the quick filter component is in an experimental state and to make it stable we want to collect here the feedback and check what is needed to make it stable.

> If you have any ideas or feature request please comment them on this issue. An open discussion is welcome! 

The only thing that stops me from making it stable is, that the data source requires a `name` property on every node to work with the quick filter. The filter field data source does not have the requirement. 

```typescript

export interface DtQuickFilterDefaultDataSourceSimpleOption {
  name: string;
}

```

In my opinion, I would prefer something more specific like a unique ID (the name currently works as id) maybe we should rename it to id – but this should be open for discussion.

The `name` is currently used to identify a option by its path. https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/experimental/quick-filter/src/state/reducer.ts#L151

```typescript
      // if the option is distinct we only have to check for the groups name because
      // there can only be one distinct option selected so we know immediately if it is selected
      if (distinct && parts[0] === path[0].name) {
        return true;
      }

      // if it is not distinct we have to build the full path out of the current filters to check
      // wether the path matches them provided node definition
      const dataPath = path.reduce(
        (previousValue, currentValue) =>
          `${previousValue.name}${DELIMITER}${currentValue.name}${DELIMITER}`,
      );

      // if the built path for the filters inside the array is equal to the option
      // in the provided nodeDef then we found our selected option
      if (item.option.uid === dataPath) {
        return true;
      }

```

and where the paths are built for the filters to set the `activeFilters` input on the quick-filter-group: https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/experimental/quick-filter/src/quick-filter-utils.ts

```typescript
import { DELIMITER } from '@dynatrace/barista-components/filter-field';

export function buildIdPathsFromFilters(filters: any[][]): string[] {
  return filters.map((path) =>
    path.reduce(
      (previousValue, currentValue) =>
        `${previousValue.name}${DELIMITER}${currentValue.name}${DELIMITER}`,
    ),
  );
}
```
<hr>

Regarding the HTML component structure, I would say it is working out well and we don't have to incorporate some breaking changes there as it scales and it should be possible to include further requirements.

But to be 100% sure please gather your desired features here to discuss a possible solution.

**Comment by tomheller** [comment]
We should not forget to consider #1169 and if there would be some breaking changes required for this one?

**Comment by uygaruyaniksoy** [comment]
Hi, I'm working on integrating the quick-filter component to work with our tables and I like it already. However, I have a few questions/feedback. 

We have categories in our filter-field like Application, Kubernetes pod etc. The filter field of the quick filter works fine with this. However, in this case side bar wasn't able to list the suggestions. Please see the following:
![categorized-suggestions](https://user-images.githubusercontent.com/20678081/89638526-47df1c00-d8ac-11ea-88b2-59507f0d7713.png)
The dataSource in this case is of the following form(options and autocomplete is nested into each other):
![image](https://user-images.githubusercontent.com/20678081/89639292-9214cd00-d8ad-11ea-8d46-01d9fac3b4c1.png)

If I flatten the hierarchy and remove the categories, it works fine as expected like in the following picture:
![flattened-suggestions](https://user-images.githubusercontent.com/20678081/89639510-f8015480-d8ad-11ea-8d91-793e3f78a8ec.png)

Is there something wrong with my dataSource. Having the categories is important for us, is this a known problem or are there any plans to implement this feature?

Also, as can be seen from the last picture, in the sidebar suggestions, non-distinct suggestion checkbox render nicely but the radio buttons, which should be in the first quick-filter-group are missing but I don't get any errors anywhere.

The mentioned '**Show More...**' feature or a limit would be very nice as currently the sidebar can get very tall very quickly. Is there a PR for it already?

Finally, some filter suggestions take a long time to load, it would be nice to have an option to set the loading indicator of dt-filter-field inside.

Thanks

**Comment by christian-fischer** [comment]
One thing I noticed when using the `quick-filter` in cluster inside the `page-content` component:
There's too much spacing around the sides. The _page-wrapper_ from the `page-content` already defines a 20px margin; on top of that, the `quick-filter` additionally defines a 20px padding; so that's 40px of spacing

**Comment by christian-fischer** [comment]
Hi @lukasholzer, after CARPE did some exploratory checks, we found the following issues:

- for asynchronously loaded options the group vanishes after selection
for an async example to reproduce see #1555 
![image](https://user-images.githubusercontent.com/5974170/92235677-625ce300-eeb4-11ea-8181-d2c60447fb76.png)
![image](https://user-images.githubusercontent.com/5974170/92235713-6c7ee180-eeb4-11ea-9328-a5d40c388010.png)

- when selecting one of the asynchronously loaded options after the group vanished, this might lead to subsequent errors
see #1522 for one of those symptoms

- we could select one of the asynchronously loaded options more than once
I think this is also just a subsequent symptom, possible because no proper path can be determined with the group gone
![image](https://user-images.githubusercontent.com/5974170/92236585-fd09f180-eeb5-11ea-97e0-70cceefa8bbe.png)

- after loading asynchronous options, the sidebar is empty
for an async example to reproduce see #1555 
![image](https://user-images.githubusercontent.com/5974170/92235758-86202900-eeb4-11ea-8ba5-bff5b12ab2e8.png)
![image](https://user-images.githubusercontent.com/5974170/92235737-7a346700-eeb4-11ea-8be2-208febf32286.png)

- with wide content in the quick-filter content area, there is a gap visible when collapsing the sidebar
see #1559 for more details and how to reproduce
![image](https://user-images.githubusercontent.com/5974170/92236130-16f70480-eeb5-11ea-82c7-2aea9762365b.png)

**Comment by ffriedl89** [comment]
@lukasholzer Can we close this issue now, since the component is stable?

**Comment by lukasholzer** [comment]
@ffriedl89 no @NinaKammerlander is working on it it is a bug technically in the drawer

**Comment by lukasholzer** [comment]
It is already stable
