### ISSUE TITLE
Filter field improve types

### ISSUE THREAD

**Issue by thomaspink** [dynatrace-oss/barista#149]

**Comment by heartdisease** [comment]
The typing for `added`, `removed` and `filters` in `DtFilterFieldChangeEvent` is quite inaccurate since the first element in the "string" array is always an object which seems to come directly from the object you initialized the data source for the filter field with.

I think a more honest typing than `T[][]` would be something like `[any, ...T[]][]` or `[object, ...T[]][]`.

**Comment by thomaspink** [comment]
@heartdisease can you provide an example, because the types you mentioned are actually correct.

**Comment by ffriedl89** [comment]
@thomaspink is this linked to any of your recent PRs 
If so, please link the issue with the PR

**Comment by thomaspink** [comment]
Should be solved with the latest typing PRs
