### ISSUE TITLE
Fluid-Elements: Design System Provider

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1515]
# Feature Request

Create a `design-system-provider` packages that handle global styles and variables.

There is a really nice example how to approach this from FAST: https://fast.design/docs/components/design-system-provider/.

I would start implementing the same :D As this seems to handle all use cases of handling space etc.

**Comment by SkaillZ** [comment]
As far as I understand, the approach from FAST sets some default values and provides a way to customize design tokens by allowing to override specific values. However, I'm wondering if this is the right approach for us since since we're actively prohibiting modifying most tokens in other areas (e.g. by using SASS variables instead of custom properties, using the Shadow DOM etc.). If we want prevent users from overriding tokens, I think this component should only be responsible for setting the theme and required default styles so the only inputs would be the theme and maybe some other high-level options like in this one: https://fluentsite.z22.web.core.windows.net/components/provider/definition

**Comment by lukasholzer** [comment]
I think @tomheller has a strong opinion on that.

My understanding of the Design system provider is to handle some default values so that the user doesn't have to set them on every component. like theming etc..

Furthermore, it should take care of shipping some base styles so that not the component has to take care of it. IMO we can define that when you want to use a component correctly you have to wrap it in the provider as the provider sets the needed defaults.

**Comment by tomheller** [comment]
Yes, the design system provider contains some defaults that it will provide down to the individual components within it's slot. 
Some of these properties are calculated within the design system provider (in FASTs example. This is where the design units input goes... it calculates certain spacings ect...). 
I think this is a good approach to look at. I am more and more unsure about the use of sass variables here. At this point, we cannot use the sass variables in our components, an having all tokens available as custom properties would make a lot of things way easier. 

Consider a layout wrapper, that can rebind spacings based on a single input of `layout ='loose|dense`. Prohibiting changes in the tokens should not be our primary goal at this point.

**Comment by SkaillZ** [comment]
# API Proposal

## Overview

The `fluid-provider` ensures that all required properties are set to display child components correctly. It allows configuring the theme and layout density (relative spacing) of child components.

## API
### fluid-provider
#### Properties and default values:
```typescript
theme: 'abyss' | 'surface' = 'abyss'; // Theme to use inside the provider
layout: 'dense' | 'loose' | 'default' = 'default'; // Layout density
displayBackground: boolean = false; // Whether the provider should use the theme's background color. If false, this no background color will be set on this component.
```

#### Events:
none

### HTML prototype

```html
<fluid-provider theme="surface" layout="dense" display-background>
  <fluid-button>
     ...
  </fluid-button>
</fluid-provider>
```

**Comment by tomheller** [comment]
I think the provider should not apply actual layout. I would remove the `display-background` property.

**Comment by SkaillZ** [comment]
Alright, then I'll add a remark that a container with the background color should be created manually.

Not sure how the spacing rebinding should work. Maybe define new properties `layout--small`, `layout--medium`, `layout--large` that correspond to the [spacing tokens](https://github.com/dynatrace-oss/barista/blob/master/libs/shared/design-tokens/generated/global/spacing.ts) and only apply them to some spacings (e.g. the vertical padding on the button). It could "shift" the spacings according to the setting so that `layout--medium == spacing--small` if a `dense` layout is used. With a `default` layout, there would be no difference between `spacing--medium and layout--medium`.

**Comment by tomheller** [comment]
I would rather see something that kind of uses some logic that has a set of default spacings, and when set to dense, it collapses / devides the spacing token values to less. I.e. 
```ts
import { FLUID_SPACING_SMALL } from '@dynatrace/fluid-design-tokens'`
...
// wherever the custom properties are set within the design-system-provider
if (this.layout === 'dense') {
  this.style.setProperty['--fluid-spacing-sm'] = `{FLUID_SPACING_SMALL * 0.5}px`;
} 
// ...
```
This is obviously some flawed code, but I guess the idea comes across. I don't know how to provide custom properties best on a custom element. 
Additionally we would probably need unit-less value imports to be able to apply calculations. 
But this is what I think the fast provider does as well.

**Comment by lukasholzer** [comment]
We will close this issue as web components are not the way we want to create components in the future this is related to a shift of priorities in the team.
