### ISSUE TITLE
[FluidComboBox] How to display selected items in the combo-box

### ISSUE THREAD

**Issue by peter-affenzeller** [dynatrace-oss/barista#1527]
# Feature Request

Properly display selected options in the fluid-combo-box.

## Summary

Since we provide the possibility to pass a custom render function, the options of the combobox can be anything, so we can't just display the selected option's value in the input field (and truncate as soon as the text is too long to fit...) like this:
![Screenshot 2020-08-26 at 11 30 48](https://user-images.githubusercontent.com/52814847/91287429-05647d00-e790-11ea-9323-50c573969efe.png)

Either the user has to provide something like a `displayvalue`, or we have to tackle this another way. Any suggestions?

We could implement something like pinned selected options at some point, so that when you open the popover, all the selected options are displayed on top of the list...

**Comment by lukasholzer** [comment]
An option needs a value anyway and I would call simply the `toString()` method on the option nothing fancy but should work for the first solution.

**Comment by heartdisease** [comment]
I'd suggest to add a new input for rendering the display string for the currently selection option:

### Inputs

| Name           | Planned for | Type     | Default | Description                                                                      |
| -------------- | ----------- | -------- | ------- | -------------------------------------------------------------------------------- |
| displayNameFunction | MVP         | `(option: T) => string` | (option) => \`${option}\` | Function that returns a display string (no HTML allowed) for a given option.                                              |

I've already posted this in the original component API proposal. After thinking about it for a while, I don't think having HTML displayed in the input is a valid use case. There should always be a non-HTML variant for each option that is selectable.

Just using `.toString()` is an option I'd rather not want to use since it is rather impractical for every non-primitive data type. Having to create your own class just to overwrite `toString()` seems like unnecessary overhead to me if you can just provide a pure function doing the same thing for every option.
