### ISSUE TITLE
Support values in dt-tag-add component

### ISSUE THREAD

**Issue by preiserphilipp** [dynatrace-oss/barista#1532]
# Feature Request

## Summary

We want to be able to specify values when creating manual tags in the UI. 

## Feature Description

We are currently working on allowing the specification of tags as key-value-pairs in the GWT UI. We need to adapt the angular component "dt-tag-add", to also support this. Below you can find a screenshot of how this could look. This new dialog, however, does not replace all usages of the old one. Some screens, like Dashboards, only need to specify keys.

## Attachments

![3_hostpage_top PNG](https://user-images.githubusercontent.com/70329390/91450083-2d310f00-e87c-11ea-8a21-f200a15aee97.jpg)

**Comment by lukasholzer** [comment]
Hey, @preiserphilipp thank you for opening the feature request. I think this is a very cluster-specific approach for creating tags. Therefore I don't see any overlap with other consumers of the barista components. 

I would suggest creating a higher-order component in the cluster that uses the barista tag component to create this overlay.

The barista components are a shared basis of all the different Dynatrace UI parts. If you find any other team outside the cluster that would need this component please add it here otherwise we will close this feature request.

**Comment by sleepomeno** [comment]
The dt-tag-list already supports a dt-tag-key for _displaying_ a key-value tag, therefore I think it would make sense to also support adding one. 
In general, key-value tags are quite common and also used outside of Dynatrace

**Comment by PhilippGrasboeckDynatrace** [comment]
Hey, I have a customization for the "add-tag" button too.
My use case is: I want to add tags, but only from a list of allowed strings. Therefore, I will like to be able to customize the "Add tag" popup, or to somehow define the list of allowed strings. Instead of the textbox, there should be a combobox. The list of allowed strings is somewhat large, in my case, they are Jira components, and there are hundreds.

**Comment by tomheller** [comment]
As it seems there are a couple of customization requirements, and we probably will not be able to include them all into the barista library, maybe a more generic approach would fit here. 

I.e. provide a custom component, that will need to extend from `DtTagAddCustomInput` (to provide a selector for the projection) and implement a certain interface, to be able to communicate correctly with the tag-list component. 
This component could be provided via template projection to the tag-add button something like this:

```html
<dt-tag-list aria-label="A list of tags showing custom groupings.">
  <dt-tag *ngFor="let tag of tags">{{ tag }}</dt-tag>
  <dt-tag-add
    placeholder="insert tag name here"
    aria-label="tag input"
    (tagAdded)="addTag($event)"
  >
   <my-custom-tag-add-form></my-custom-tag-add-form>
</dt-tag-add>
</dt-tag-list>
```

Would something like this serve your purpose @sleepomeno @PhilippGrasboeckDynatrace ?

**Comment by ffriedl89** [comment]
Moved to internal issue tracking

**Comment by sleepomeno** [comment]
> Would something like this serve your purpose @sleepomeno 
@tomheller  yes it would
