### ISSUE TITLE
Tree-table does not recognize column when it's in its own component

### ISSUE THREAD

**Issue by leonschloemmer** [dynatrace-oss/barista#1560]
# Bug Report

## Expected Behavior

The tree-table should recognize the `dtColumnDef` on a ng-container which is in another component than the table

## Current Behavior

The tree-table is unable to find the column and throws an error: `Could not find column with id "..."`

## Steps to Reproduce

https://stackblitz.com/edit/github-y46ecj?file=src/tree-table/tree-table-simple-example/tree-table-simple-example.html

## Context (Environment)

I am working on the Angular version of the waterfall in the MDA of Synthetic Browser Monitors

### Used Versions:

- **node**: >=10.13.0
- **npm**: 6.14.4
- **typescript**: 3.8.3
- **angular**: 9.1.12
- **@angular/cdk**: 9.2.4
- **@dynatrace/barista-components**: 7.6.0

**Comment by ffriedl89** [comment]
@leonschloemmer I've checked the code and this is a not yet supported feature for the tree-table. Currently only the dt-table can handle simple-columns. We need a couple of functions on the table class to properly register simple tables in the table lifecycle. This feature would result in quite some effort to implement right now, since we can't just switch the constructor that now requires an optional DtTable instance.

One approach could be to create an interface for the functionality of registering the simple columns with the column and the table and the tree-table implement this interface. The DtTreeTable then needs to provide itself as a DtTable for Angular's DI. This would mean that the DtSimpleColumnBase would receive the TreeTable instance and register itself correctly. 

If you really need the feature we would highly appreciate if you could contribute this to the library. 
Unfortunately this is not high on our priority list at the moment.

**Comment by ffriedl89** [comment]
Currently not on our roadmap
