### ISSUE TITLE
quickfilter: selected options should always be visible

### ISSUE THREAD

**Issue by hubert-grininger** [dynatrace-oss/barista#1754]
# Feature Request

For example:

We have these options inside a group:

- option 1
- option 2
- option 3
- option 4
- option 5
- option 6

maxGroupItems = 5, option 6 is invisible.

Now users clicks "Show more" and selects option 6 then show more is closed. The selection of option 6 is now not visible anymore. This is not very handy and may be considered as a bug by users.

As a fix I would imagine that selected options are sticky, meaning they are always visible. Not sure if there should be an option to disable this behavior as it feels rather natural to me.

Thanks.

**Comment by ffriedl89** [comment]
Hey @hubert-grininger, thanks for your input. A couple of questions come to mind.

Where would you suggest that the option sticks? Reordering options on selection is not a good idea and might be very confusing. Can you please provide a more detailed description what sticky would mean?
For radios this is making the selection "sticky" can work since there is only one selected, what about checkboxes though, there might be many selected and spread across a long list - how would this work there? 
The selection is always visible in the filter field above - so it is not invisible in general, but I get the point that it might be interpreted that way.

**Comment by hubert-grininger** [comment]
Hi Fabian,
I basically would suggest that selected options are always visible (also when only the maxGroupItems are shown). Otherwise you miss that an option is selected (as it's hidden in the "view more" section).

An example how  I envision that:
Initial state:

Option 0
Option 1
Option 2
Option 3
Option 4
[View more](url)

Use click view more:
Option 0
Option 1
Option 2 => select
Option 3
Option 4
Option 5
Option 6
Option 7 => select
Option 8 
Option 9 => 3. gets selected too

Option 0
Option 1
Option 2 [X]
Option 3
Option 4
Option 7  [X]
Option 9  [X]
[View more](url)

**Comment by ffriedl89** [comment]
I think this approach is a good idea - thx for clarifying what you meant by making it sticky. 
The addition of this feature makes total sense and I like your approach. Since there is no select button and all options would get sticky we can anticipate a rather small number of options selected at any time. 

This would be a very good fit for a contribution. The change should be rather small and from a quick look I think only the `_getOptions` method in https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/experimental/quick-filter/src/quick-filter-group.ts#L231 needs to be adjusted.

**Comment by hubert-grininger** [comment]
Thanks for comment - we will schedule this for our team!

**Comment by ffriedl89** [comment]
Moved
