### ISSUE TITLE
EventChart: Overlay still visible in Event chart

### ISSUE THREAD

**Issue by subarroca** [dynatrace-oss/barista#198]
# Feature Request
In Event Chart, on programmatically scrolling on select, the overlay is still open. And when clicking outside you loose reference of the clicked event.

## Expected Behavior

Once you select an event by clicking, the overlay gets pinned (as expected). If you then add an action on select, like scroll, there should be a way to hide the pinned overlay.
But if you click outside the deselect should still work as it does now.

Also, when clicking outside the overlay there should be a way to close the overlay and keep the event selected.

## Current Behavior

Overlay still open and after click outside we loose track of selected item

## Possible Solution

Add a way to close the overlay without deselecting when calling a function.
Also add a way to `deselect()` the selected event

## Steps to Reproduce

1. Load an event chart
2. Click on an event (that has a scroll attached)
3. See that the overlay is still pinned
4. Click outside
5. See that selection is lost

## Context (Environment)

Linking this chart to a list of event and wanting to keep track of the clicked event without seeing the overlay

### Used Versions:

- **node**: 12.3.1
- **npm**: 6.9.0
- **typescript**: 3.5.3
- **angular**: 8.2.12
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 4.15.0

**Comment by tomheller** [comment]
Hi @subarroca!

Thank you for this feature request. Here is what we can propose as changes to the event-chart components.

**Add a select function**
```ts
/**
 * Selects an event based on its index in the original dataset.
 * The given value will be clamped between 0 and the length of the original dataset.
 */
select(index: number): void {}
```

**Add a deselect function**
```ts
/**
 * Deselects all events
 */
deselect(): void {}
```

**Remove deselction on backdrop click**
When an overlay is pinned and the backdrop is clicked, the overlay will close but it will no touch the selection. 

**Potential problem in user behaviour**
For the user there is now no way to deselect the current event? At first I thought it would make sense to add a toggle on the selected event (when a selected event is clicked, it will be deselected). But this could lead to a break of consistent ui behaviour, because a click on an event usually shows the overlay. 
I'm not quite sure how to handle this at this point.

**Comment by subarroca** [comment]
I think your solution will work. We'll only be missing a
`/**
 * Closes the overlay without affecting the selection
 */
closeOverlay(): void {}`
so we can call it when clicking on any function from inside the overlay, close it and just leave the selection as is

If the user clicks on a selected point with an open overlay, the backdrop should act and deselect it. If the overlay is closed, consider it's being selected again and show the overlay
