### ISSUE TITLE
DtOverlay: when triggering the overlay near the screen border it appears with a wrong width

### ISSUE THREAD

**Issue by jdbernalb** [dynatrace-oss/barista#220]
# Bug Report

## Expected Behavior

Overlay should appears with the width of the content
## Current Behavior

Overlay appears with a wrong width when triggering the overlay near the screen border 

## Steps to Reproduce

1. Go to verlay-demo.component.scss
2. Add the following style
```
span {
  display: flex;
  width: 100%;
}
```
3. Hover the overlay near the border
![image](https://user-images.githubusercontent.com/20688460/69645187-0d0ebe00-1066-11ea-8d11-613a484f24c6.png)

1. 

### Used Versions:

- **node**: 12.1.0 
- **npm**:  6.9.0 
- **typescript**: 3.5.3
- **angular**: 8.2.14
- **@angular/cdk**: 8.2.3 
- **@dynatrace/barista-components**:  4.15.0

**Comment by ffriedl89** [comment]
This is still an issue and needs to be fixed

**Comment by ffriedl89** [comment]
After investigating this issue a bit in the past, this is not easily fixable. My opinion is that we need to create a custom position strategy that calculates the position differently since the offset in the FlexibleConnectedPositionStrategy alone does not work.
The issue is somewhat hard to reproduce since the menu gives extra room to the left for the overlay trigger. If the overlay is completely on the left edge of the window without any spacing the bug is easily reproducible. 

Further testing should be done, but my best guess at the moment is that the FlexibleConnectedPositionStrategy is not flexible enough 🤷‍♂
