### ISSUE TITLE
Table: Rethink states (empty, loading)

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#287]
# Bug Report

## Expected Behavior

I want to have proper logical transitions between states (initial, empty, loading, data present)

## Current Behavior

Currently the loading and empty states are not mutually exclusive, this might be something to consider.

## Possible Solution

We should work out proper transitions - maybe all tables should be in a loading state initially until the first datasource is set, either empty or filled. Transitioning from an empty dataset to a filled dataset should maybe show a loading state in between? 

## Steps to Reproduce

1. use a dt-table and provide an empty state and a loading indicator inside ng-content and set no datasource or an empty array as the datasource and loading to true.

**Comment by ffriedl89** [comment]
FYI @Marike-Sorgdrager

**Comment by ffriedl89** [comment]
@Marike-Sorgdrager 
Provided a new approach to make states clearer for the user. 

![Screenshot 2020-01-08 at 11 12 25](https://user-images.githubusercontent.com/2905693/74009855-678c9a80-4984-11ea-9855-a873b2982340.png)
![Screenshot 2020-01-08 at 11 12 50](https://user-images.githubusercontent.com/2905693/74009857-69eef480-4984-11ea-945e-9b8ffe4baf47.png)

So we would have the following states: 
Loading
Populated/Data present
Empty
EmptyAfterData
Reloading

In the screenshots states change depending on the previous state. Which is not ideal in my opinion
If we don't differentiate between an empty state that never had any data and an empty state with previous data the states would get a lot easier. 

Loading
Populated/Data present
Empty (always showing the headers) 
Reloading

If we go a step further and the loading indicator always has a transparent backdrop we can get rid of this state as well and end up with only 3 states 

Loading (always with transparent backdrop that just overlays the table) 
Populated/Data present
Empty (always showing the headers)

**Comment by Marike-Sorgdrager** [comment]
@ffriedl89 that makes absolute sense. More than happy to simplify it into only 3 states. I think with the tables it's important to actually keep or show the headers. So if we always put an overlay over and then the loading that's perfectly fine.

**Comment by tkaiser** [comment]
I experienced a semi-related problem when using `dt-table`.

My problem was that the row-click handler did not work (the `(click)` output on the `<dt-row>` to be exact). 

I finally tracked down the problem to the following issues on my end: 
1. I set the loading indicator input on `<dt-table>` with `[loading]="isLoadingData"`
2. This boolean was initialized to `true` but I failed to set it `false` when loading was done, so the loading state was actually never removed from the table.
3. Additionally I missed that I had to set a `<dt-loading-distractor dtTableLoadingState></dt-loading-distractor>` into the `<dt-table>` element to make a loading indicator actually appear. From my understanding of the barista components that was not necessary, because with `<dt-chart>` it just shows a spinner without having to define the element. 
4. In conclusion, the loading state never getting removed prevented my click handler from working, and it was actually impossible to tell that the loading state was active because I didn't add the `dt-loading-distractor`.

I think there is some room for improvement there. I'm thinking
a) it should not be necessary to specify the distractor element or
b) a default loading distractor should be shown if the user does not define one.
