### ISSUE TITLE
Disabled attribute is not set on button when using `[dtOverlay]`

### ISSUE THREAD

**Issue by bartoszbobin** [dynatrace-oss/barista#315]
# Bug Report

Code sample:

```
<button class="arrow left"
        type="button"
        [disabled]="isPrevButtonDisabled"
        (click)="prev()"
        [dtOverlay]="overlayPrev"
        [dtOverlayConfig]="overlayConfig">
  <dt-icon name="dropdownclosed"></dt-icon>
</button>

<ng-template #overlayPrev>...</ng-template>
```
```
  readonly overlayConfig = {
    originY: 'center',
  };
```

## Expected Behavior
`[disabled]` attribue should be set on button

## Current Behavior
`[disabled]` attribue is not set on button

### Used Versions:

- **node**: 10.15
- **yarn**:  1.15
- **typescript**: 3.5.3
- **angular**: 8.2.12
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 4.15.1

## Detailed Description

Overlay shouldn't be shown for disabled state - and it's not visible

**Comment by tomheller** [comment]
@bartoszbobin You are binding a disabled property on a default html-button element. The disabled attribute is not set, because the attribute binding is not reflected in the dom. You can either add the 
`dt-button` directive to the button, which will pick up the disabled binding and will reflect the disabled property on the element, or use angulars attribute binding like this: 
`[attr.disabled]="isPrevButtonDisabled ? 'disabled' : null"` on the button. 

Does this solve your issue?

**Comment by bartoszbobin** [comment]
That's help - thanks!
