### ISSUE TITLE
Support for coloring charts

### ISSUE THREAD

**Issue by rarenal** [dynatrace-oss/barista#468]
# Feature Request

As a user I want to be able to change the color options within a chart

## Summary
Coloring a chart is not only related with esthetics, it can also be used for highlighting, comparing or theming within a chart:

- Highlighting: When having multiple series within multiple categories, I would like to highlight those series above X value, or the minimum and maximum values from each series, in order to easily find trends and meaningful insights.

- Comparing: When having multiple series within a chart, I would like to compare some of this series between them and also distinguish to which series it belongs.
          Example: I have 4 series:
                           1. serie A
                           2. serie A 7 days ago
                           3. serie B
                           4. serie B 7 days ago
          If I use different colors for the 4 series, I wouldn't be able to visually compare those series, but if I 
          apply the same color to series 1 and 2 and another one to 3 and 4 with different shades, it could 
          be easily comparable.

- Theming: When charting, I may want to use my brand's colors or switch between a dark/light mode

## Feature Description
Add the possibility of coloring different components within a chart:
    - Series (most important)
    - Axis labels
    - Axis
    - Legend labels 
    - Units
    - Overlay

The coloring should only be restricted to the use of any DtColor

**Comment by kathrin-aigner** [comment]
just wanted to add my comment from slack again:

Hi Ramón,
We are currently in the process of restructuring our entire UX team and will only work on specific roadmap items in the future. The aim here is that we can better focus on individual UX topics. This will help you in the longterm even more because we can give you consistent and adaptive components that will not only save time but also brainpower :smile: One of these roadmaps deals with developing a new design language which we want to use in the future for a more modern and usable product. One of those topics that is included with the design language roadmap are colors. We noticed that a rigid system of handpicked colors (as we currently have) does not longer work for us, which is why we also had a look into other systems which are using generative color palettes such as Lyft for example https://design.lyft.com/re-approaching-color 9e604ba22c88 
We want to go in this direction in the future because our current color system does not scale and hinders us more then it helps. Also accessibility wasn’t really a topic when these palettes were defined.
Long story short: I cannot tell you when the new color system will be available and how the process of picking custom colors would look like. It is part of our roadmap but there are other releases with higher priority.
I know that there are users that would love to have the color changing possibility as well. But I really think that we first also would need to have better color palettes. Anyways if you want to work with the existing color palettes and the topic is urgent  you can implement this feature by yourself. When doing that please remember a few things:
* always work together with the Designops team 
* try to find a solution that all teams and users can work with. 
* Our colors should ideally work with accessibility standards so that we can offer enough contrast when choosing colors. There is a guideline for this: https://styles.lab.dynatrace.org/accessibility/ and https://webaim.org/resources/contrastchecker/ can help to check the individual colors.
