### ISSUE TITLE
Show more placeholder is shown in the tag list although there are no more tags available in the tag list

### ISSUE THREAD

**Issue by bugaandreea** [dynatrace-oss/barista#603]
# Bug Report
## Expected Behavior

The tag list should not show the '0 More...' placeholder when there are no other tag components in the list to display.

## Current Behavior
The '0 More...' button placeholder is still displayed although there are no (more) tag entries. In some cases the '0 More...' disappears when clicking outside the tag list area and in some cases it is displayed for few moments and then it disappears on its own. 

## Steps to Reproduce

Please find attached a gif showing the behavior and the stackblitz for the issue.

## Context (Environment)
We are using the tag list component for displaying meaningful information when available and it misleading for the users to have a '0 More...' button when no (other) entry is available.

### Used Versions:

- **node**: 12.13.0
- **npm**: 
- **typescript**: 3.5.3
- **angular**: 8.0.0
- **@angular/cdk**: 8.0.0
- **@dynatrace/barista-components**: 5.2.0

## Attachments
![tag_list_viewer](https://user-images.githubusercontent.com/6025874/74638975-4179ae00-516d-11ea-923c-a7de51b51b5c.gif)

StackBlitz: [link](https://qgnirvwwa.github.stackblitz.io/)

**Comment by ffriedl89** [comment]
@bugaandreea Thanks a lot for reaching out and providing a very good description!

We will investigate this issue and update you here :)

**Comment by tomheller** [comment]
After some investigation, it seems that the problem does not lie within the tag-list, as originally thought but in the way the tree table is being re-rendered after expanding. 
The tag-list needs one additional render cycle to figure out how many elements would be hidden / shown, but the detached functionality of the tree-table render cycle seems to not trigger a repaint because the data did not change.
