### ISSUE TITLE
EmptyState: Investigate ResizeObserver for proper layout handling

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#648]
# Feature Request

## Summary

As part of progressive enhancement, we should investigate the resizeobserver for the empty state component to get rid of the _updateLayout call. Make the component aware of it's container view (hello container queries)

## Feature Description

The current problem we have is that the empty-state component is used in multiple parents and "extended" versions of the component by using the dtCustomEmptyState directive and we would need to handle _updateLayout for each scenario.
By using the resize observer we would transfer this logic into the empty state since the component itself is aware of the container's width.

**Comment by tomheller** [comment]
I will look into this one! First thing I noticed that typescript does not ship types for it within `lib.dom` because it is still marked as EditorsDraft in the spec. See issue https://github.com/Microsoft/TypeScript/issues/28502
That should be fixable by declaring it, but the typesaftey will be a bit off. 

This is what we get back from the ResizeObserver, if we observe the container element of the `DtEmptyState`. This seems like we can work with that.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/6338434/75416220-05dda180-592e-11ea-8c99-5779e90dc614.png">
