### ISSUE TITLE
filter-field: Autocomplete not working after two consecutive filterings

### ISSUE THREAD

**Issue by W3D3** [dynatrace-oss/barista#649]
## Steps to Reproduce

1. Select any filter key, type to use filter suggestions (works)
2. Confirm selection
3. Select any filter key, filter suggestions stop working

After the second consecutive filtering, the auto-completion stops working. See this GIF:
![barista_filter_autosuggest_bug](https://user-images.githubusercontent.com/1103924/75344873-d1b9a080-589b-11ea-9858-669357670128.gif)

## Context (Environment)

Works on the internal dynatrace barista demo page: https://barista.lab.dynatrace.org/components/filter-field

### Used Versions:
Also reproduced it locally:
- **node**: 12.16.1
- **npm**: 6.13.7
- **typescript**: 3.5.3
- **angular**: 8
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 5.2.0

### Additional Points

I would expect that on the second filtering when I press backspace to delete the character 'a', only the character and not the whole filter key gets deleted.

**Comment by ffriedl89** [comment]
Hey @W3D3, thanks a lot for reporting this issue. I could already track down the issue. This is a nice edge case. 
The issue is that when we reset the input value after a filter is selected, the input does not fire an input event anymore. So the next time you enter the same character again - e.g. filtering twice for a lowercase "a" the second emission does not get handled.

We will patch this and it should be a rather easy fix.
