### ISSUE TITLE
Keyboard action snaps the selection area in chart

### ISSUE THREAD

**Issue by perihan-rashed** [dynatrace-oss/barista#727]
# Bug Report

## Expected Behavior

There should be no snapping behaviour at all in the chart.

## Current Behavior

When using the selection area in the chart component, and selecting an area that is not selectable with the combination of pressing any key on the keyboard, the selection area snaps.

## Steps to Reproduce

https://stackblitz.com/edit/github-w3zgm7?file=src/chart/chart-selection-area-default-example/chart-selection-area-default-example.html

![selectionarea-bug](https://user-images.githubusercontent.com/62100118/76521417-15e49d80-6465-11ea-9c13-0a557272b325.gif)

1. Select a minimum area (where the selection is disabled)
2. Press any key on the keyboard

### Used Versions:

- **angular**: "9.0.4"
- **@dynatrace/barista-components**: "6.0.1"

**Comment by tomheller** [comment]
@perihan-rashed 
What would be the expected behavior of a keyboard press, when the currently dragged range is not valid. 
I think when the selection area was initially speced, the decision was to grow the selection area to it's _minimal valid range_ to make it quicker for the user to actually get to a valid result. 
Otherwise they would have to hit the keyboard shortcuts multiple times, stepping from one invalid range to the next one until they reach a valid range. 

What would be the benefit of removing the current behavior and what would be the alternative.?
