### ISSUE TITLE
Sunburst chart

### ISSUE THREAD

**Issue by subarroca** [dynatrace-oss/barista#786]
# Feature Request

## Summary

Drill down pie chart with multiple levels

## Feature Description

Initial view: One

-  level (typical) pie chart.
- On clicking in one of the slices a new outer arc appears delimited by the angles of the parent.
- This drilldown should keep happening for multiple levels
- 
- When selecting a segment:
1. initial level should be greyed out
2. all the ancestors should be coloured,
3. all the ancestors direct siblings should be greyed out
4. all children of selection should be coloured
5. any other segment should be hidden
- Initial structure should be {name, key?, value?, children?} either value or children should be provided
- When selecting one segment outputs should be:
1. the whole path
2. array of pairs [key,name] for all selected path
- Color should be taken as default from chart palette, but also color could be specified for every slice

## Attachments

<img width="361" alt="Screen Shot 2020-03-23 at 2 55 30 PM" src="https://user-images.githubusercontent.com/1245057/77332551-7a83e000-6d22-11ea-9c52-485bb15bd597.png">
<img width="340" alt="Screen Shot 2020-03-23 at 2 55 39 PM" src="https://user-images.githubusercontent.com/1245057/77332562-7d7ed080-6d22-11ea-8112-847474e8ddec.png">
<img width="350" alt="Screen Shot 2020-03-23 at 2 55 50 PM" src="https://user-images.githubusercontent.com/1245057/77332565-7e176700-6d22-11ea-8578-2e77cd8d1230.png">
<img width="365" alt="Screen Shot 2020-03-23 at 2 56 46 PM" src="https://user-images.githubusercontent.com/1245057/77332570-7eaffd80-6d22-11ea-9233-fccbe0c9c2ad.png">

**Comment by subarroca** [comment]
I already started implementing this one

**Comment by tomheller** [comment]
Hi @subarroca! This feature request for a sunburst chart looks amazing and also that you are already taking care of contributing this one makes us extremely happy 😄 . 

When you have a decent understanding of how the API for this component would look like, it would be great if you could outline it here as sort of an API proposal. 

For completely new components we like to do this to make sure that we can keep a consistent feel of the API throughout the components library (For inspiration, see the [slider issue](https://github.com/dynatrace-oss/barista/issues/204#issuecomment-585196766) where @bardosmisi did this for the new slider component).

**Comment by subarroca** [comment]
```html
<dt-sunburst
  [data]="data"
  [selected]="selected"
  (selectedChange)="onSelect($event)"
  >
  <dt-sunburst-overlay>...</dt-sunburst-overlay>
</dt-sunburst>
```

## inputs
**data: SunburstNode[]** whole tree of information. For every node either children or amount should be provided. Amounts will be calculated based on children's values
**selected: Array<string,string|number|boolean>[]** Ordered array of [filterKey,filterValue]
**disabled:boolean** if the component should be disabled (default:false)

## outputs
**selectedChange: EventEmitter<{[key:string]:string}>** Ordered array of [filterKey,filterValue]

## content projection
* **dt-sunburst-overlay** (could be a default overlay if we don't need to customize it)

## interface
```ts
SunburstNode {
  filterKey: string;
  filterValue: string|number|boolean;
  label: string;
  value?: number;
  children?: SunburstNode[];
}
```

* **filterKey** Key to be added as [filterKey,filterValue] to the pairs output
* **filterValue** Value to be added as [filterKey,filterValue] to the pairs output
* **label** Label to be shown in the chart
* **value** Optional if children provided. Absolute or relative number to be represented in the chart
* **children** Optional. Nodes that depend on this one

# Alternative
* Instead of passing the tree of data we could do that through children ng nodes but I don't think it's worth because of the conversion back and forth that would mean

**Comment by ffriedl89** [comment]
Hey @subarroca thanks for the api proposal!

A couple of thoughts: 

1. Inputs
1.1 data
I'd suggest the name `series` since we have this in other charts already. 
For the type `SunburstNode` please prefix the type with `Dt`. 
I think we can omit the filterValue and filterKey properties on the type. More on that later - because I think we can remove the `SunburstStep` type.
1.2 selected
I think the type should be an array of `DtSunburstNode`. 
1.3 disabled
Why do we need disabled? Is there a usecase for this not to be interactive? 
2. Outputs
2.1. selectedChange
The type here  can be `Eventemitter<DtSunburstNode[]>`

If we handle selection with a map that uses the filtervalue and keys we end up with an event where the consumer needs to add additional logic to find the selected nodes passed to the chart. This is an unnecessary step - we can give the consumer each node in each level that is selected in the event and there is no need to traverse and match nodes to filter values. This was a learning we had in the filter field already and it proved to work a lot better if we returned the entire selected node instead of a string based match.

**Comment by subarroca** [comment]
✅ prefix with Dt 
✅ `series` better than `data`
✅ remove disabled
✅ complete node for `selected` and `selectedChange`

About this selected, the original series is a tree. Would you prefer to keep the tree structure or an array of ordered nodes?
Also, as one of the use cases is done to filter visually, it would make sense to return a  `{[filterKey]:[filterValue]}`. Would you provide it in a separate output? Maybe provide a function that transforms this?

**Comment by subarroca** [comment]
Also 2 more inputs should be added
* **allTitle**: for the initial 'All' that should be i18n
* **percent**: to indicate if the values should be shown in percentage instead of absolute

**Comment by tomheller** [comment]
This one looks already pretty good. A couple of things I would like to discuss though:

### SunburstNode
Could you explain why the value is optional in this one? I assume that a chart element will need a value to justify its existence?

### SelectedChange
I agree with @ffriedl89 here that this could be of type `Eventemitter<DtSunburstNode[]>`. Even if the inner elements contain a lot of children, this will still be easier to get the actually selected elements. 
My guess is that adding additional logic based on filterKey and filterValue to find the selected within the tree will add additional complexity. 

### allTitle
I'm not entirely happy with the name to be honest, as it does not communicate what it is supposed to do. I was thinking more along the line of `defaultTitle` or `noSelectionTitle`. But I'm also not entirely happy with these ones :(

## percent
Instead of using `percent` as a boolean switch to change the display mode of numbers, I would suggest something like `valueDisplayMode: 'percent' | 'absolute'`. This will make it more expressive and even extendable in the future.

**Comment by subarroca** [comment]
* The value is optional only if you have children, because we can build those values up, so in the end this chart will have all the values but the user doesn't need to provide values for all of them

* selectedChange will be a tree with only one child per node, so we can have the whole path.  Is that ok? Also it would make sense to return a `{[filterKey]:[filterValue]}`. Would you provide it in a separate output? Maybe provide a function that transforms this?

* I agree that allTitle is not a good name, I'll keep thinking

✅ `valueDisplayMode: 'percent' | 'absolute'`

**Comment by ffriedl89** [comment]
> selectedChange will be a tree with only one child per node, so we can have the whole path. Is that ok? Also it would make sense to return a {[filterKey]:[filterValue]}. Would you provide it in a separate output? Maybe provide a function that transforms this?
I think this is also problematic since you can't do an equals check from the node you get back from the event with the node that you passed into the series. 

I would go a route where you return an array containing the node for each layer selected.

So think about a series like: 
```
series = [
  {
    label: 'Chrome',
    children: [
      { label: 'Chrome 4', value: 1.2 },
      { label: 'Chrome 80', value: 90 }
    ]
  },
  {
    label: 'Internet Explorer',
    children: [
      { label: 'Internet Explorer 11', value: 2.8 },
      { label: 'Internet Explorer 10', value: 7 }
    ]
  }
];
```
So if a user selects Chrome 80 the event would have the following array as the payload :
````
selected = [
  {
    label: 'Chrome',
    children: [
      { label: 'Chrome 4', value: 1.2 },
      { label: 'Chrome 80', value: 90 }
    ]
  },
  { label: 'Chrome 80', value: 90 }
];
```
In that case you have the same objects and the whole path to the end of the selection. 

I also checked other components for naming of the event - the event-chart uses `selected` and I think it fits for that as well..

**Comment by kathrin-aigner** [comment]
lgtm! :)

**Comment by subarroca** [comment]
As a compilation, I think the API should be:

```html
<dt-sunburst
  [series]="series"
  [selected]="selected"
  noSelectionLabel="All"
  valueDisplayMode="percent"

  (selectedChange)="onSelect($event)"
  >
  <dt-sunburst-overlay>...</dt-sunburst-overlay>
</dt-sunburst>
```

## inputs
**series: DtSunburstNode[]** whole tree of information. For every node either children or amount should be provided. Amounts will be calculated based on children's values
**selected: DtSunburstNode[]** Ordered array of `DtSunburstNode`. (i.e. [A, A.a, A.a.1])
**noSelectionLabel: string** Label to be shown when there's no selection (i.e. All)
**valueDisplayMode: DtSunburstValueMode** Format of display for values. Default  `DtSunburstValueMode.ABSOLUTE`

## outputs
**selectedChange: EventEmitter<DtSunburstNode[]>** Ordered array of `DtSunburstNode`

## content projection
* **dt-sunburst-overlay** (could be a default overlay if we don't need to customize it)

## models

```ts
interface DtSunburstNode {
  filterKey: string;
  filterValue: string|number|boolean;
  label: string;
  value?: number;
  children?: DtSunburstNode[];
}
```

* **filterKey** Key to be added as `DtSunburstNode` to the pairs output
* **filterValue** Value to be added as `DtSunburstNode` to the pairs output
* **label** Label to be shown in the chart
* **value** Optional if children provided. Absolute or relative number to be represented in the chart
* **children** Optional. Nodes that depend on this one


```ts
export enum DtSunburstValueMode {
  ABSOLUTE = 'absolute',
  PERCENT = 'percent',
}
```

**Comment by ffriedl89** [comment]
Two small thing i think you missed is the removal of the filterValue and filterKey ;) There is no need since there is no pairs output anymore. 

In think we can use a uniontype `'absolute' | 'percent'` and don't need an enum for that

**Comment by subarroca** [comment]
Since we want to use this object to be able to filter I think it's good we keep `filterValue` and `filterKey` though we could also think of it as an extension, but as far as I've seen this could be very useful

About the enum. Usually when we want to use things from barista in our code we usually need some of those enums and we end up by replicating them in our code so I'm in favor of keeping those enums as much as possible

**Comment by tomheller** [comment]
I don't think that every consumer of the sunburst chart would need the `filterValue` and `filterKey`. I personally would opt to not include them in the standard interface provided by the component library. If a consumer needs them, they still can extend from the SunburstNode interface and add their own filters. 

Why do you need to recreate the enums? I guess I don't quite understand why you would need it and why an union type would not be enough here? Even with a union type, you have type safety in templates and ts files. Can you explain why you would go with enum over union type.

**Comment by ffriedl89** [comment]
I totally agree with @tomheller about the `filterValue` and `filterrKey` - we don't need it for the component therefore it does not make sense to force the consumer to have these fields in there. It's quite counterintuitive. If you have a usecase for your code you can always extend from the interfaces provided in your code. 

Regarding enums: 
Enums bloat bundles quite a lot if not made constant. We avoid them as much as possible or make them const. I am interested in the benefits for you - since this is some very good feedback for the library!

**Comment by subarroca** [comment]
Ok about removing `filterKey` and `filterValue` but then we'll depend just on the label to identify a node on each level. So we would not have 'Chrome', 'Chrome', 'Internet Explorer' but just one 'Chrome', which makes sense to me.

About the enums. We try to avoid hardcoding strings in our code, so if barista exported those enums we could do 
```
valueDisplayMode= "{{DtSunburstValueMode.PERCENT}}"
```
instead of
```
valueDisplayMode="percent"
```
We've been dealing with that in filters, for instance, to know if a field was autocomplete, or range or free text and in the end we create an enum on our side just to replicate the one in barista

**Comment by tomheller** [comment]
>Ok about removing filterKey and filterValue but then we'll depend just on the label to identify a node on each level. So we would not have 'Chrome', 'Chrome', 'Internet Explorer' but just one 'Chrome', which makes sense to me.

we have found during iterations of the filter field that the data passed into the system is very versatile. By creating a base `SunburstNode` interface that contains everything that the component itself needs to display the sunburst and let the consumer extend it with whatever metadata or identification data without forcing them to use `id` or any other specific name will probably enable a lot of consumers to use the sunburst more easily, without needing to do a lot of data-massaging before.

**Comment by subarroca** [comment]
I get it, but we also need a way to match the input of `selected` with the the nodes in `series`, that's what my comment was about. I'm ok with removing `filterKey` and `filterValue` but then we can only verify with `label` which is ok but then siblings cannot repeat labels, which makes sense to me but we have to be conscious of that

**Comment by ffriedl89** [comment]
@subarroca you can also do an instance check for the selected since we are returning the same object :)
