### ISSUE TITLE
DrawerTable: there is no way to close the drawer on a small-screen and animation of closing needs to be fixed

### ISSUE THREAD

**Issue by madina705** [dynatrace-oss/barista#843]
Currently in the dt-drawer-table component there is no way to close on a small-screen since drawer content overlays the table and close was only possible by clicking on the current row. One of the possible solutions is to add default close button to the content of the drawer.

Moreover, closing animation should also be fixed. The animation is broken, because we don't how wide the drawer can get.

**Comment by lukasholzer** [comment]
Thank you very much for pointing this out. 
I think the best solution would be to add an input on the drawer that disables the `overmode` for small screens. 

Because I think from a UX perspective we should create an exception for the drawer table here.
This means that the drawer in the drawer table always draws the content to the side instead of overlaying on smaller screens like it is currently.

### over mode:
![image](https://user-images.githubusercontent.com/11156362/78877508-3ea28780-7a51-11ea-8205-9f7154f84708.png)

### side mode
![image](https://user-images.githubusercontent.com/11156362/78877544-4eba6700-7a51-11ea-8beb-db595c2651ec.png)


@dynatrace-oss/ux-core what is your opinion on that?
