### ISSUE TITLE
Table: Add virtual scrolling feature 

### ISSUE THREAD

**Issue by Tomasz-Jasinski** [dynatrace-oss/barista#879]
# Feature Request

## Summary

Currently Table component usage is limited as all rows are projected into DOM. Scrolling performance drops down as we add rows to the table. This request aims to add virtual scrolling possibility so that performance would be not affected by table size. Pagination is not an option because of poor user experience.

### Functional requirements

- Constant number of rows inserted into DOM regardless actual rows to display count.
- Page vertical scrollbar engaged to virtually scroll table content (no individual table scrollbar) - we don't want to end up with 2 scrollbars.
- Callback to request records for given page (within given range).
- If implemented on existing Table component basis, feature should be optional.
- Optional: two modes: 
    Finite scroll: we know total records count so proper table height may be set during initialization. Smooth scroll slider movement when scrolling.
    Infinite scroll: table height increases when scrolling down and reduces when scrolling up. Scroll slider may jump when subsequent records are loaded.
- Optional: loading distractor displayed when waiting for requested records.

### Possible solution

- Prerequisite: all rows have same and known height.
- First table row displays no data, works as a placeholder that has various height.
- Initially Table pulls limited (let's say 100) records from data source (from index 0). Placeholder height equals 0.
- On scroll event, when viewport is near the end of loaded rows, some records from the top are substituted by placeholder and subsequent page of records is requested. E.g. placeholder height is adjusted to 40 x row height and records 40 - 140 are pulled and displayed. Calculation takes table offset relative to viewport into account. 

### See also

- Solution similar to described, but using table (not page) scrollbar: https://stackblitz.com/edit/cdk-virtual-table-sticky-header-my2ikm?file=src%2Fapp%2Fapp.component.ts
- Example of performant infinite scrolling page: https://www.scnsrc.me/category/films/  (make sure AutoScroll switch on the bottom is ON)

**Comment by tomheller** [comment]
Thank you @Tomasz-Jasinski for reporting this. We obviously want to provide a performant way of dealing with so many rows in tables. 
I am curious what the @dynatrace-oss/ux-core stance on virtual container scrolling in tables is. As @Marike-Sorgdrager is the table ux support her input would be quite valuable as well.

**Comment by ursula-wieshofer** [comment]
Hi @Tomasz-Jasinski,
thanks for bringing this up. From a UX perspective virtual container scrolling brings a lot of difficulties with it (how to make sure the table indicates scrolling is possible, how to make sure users can distinguish it from a standard table,...) It is really not recommended to use container scrolling.
Another UX issue is showing such a huge table at once, as users normally don't need all the entries at once, we recommend to focus on filter possibilities rather than focussing on scrolling possibilities. I'd need to know the exact use case to really help you with this, but users normally are not "working" with the whole table, but rather with a subset.

**Comment by SkaillZ** [comment]
@Tomasz-Jasinski Could you please provide some more details on your specific use case?

**Comment by Tomasz-Jasinski** [comment]
Thank you @ursula-wieshofer and @SkaillZ for feedback. 
**Use case**
Our use case is to show log files, one log line per table row. But we do not need thousands of rows to utilize virtual scrolling. Just several hundred of them causes noticeable slowdown - especially when one row consists of many columns and/or uses several DOM elements underneath. I've tested 7 column table: scrolling performance drops from ~60 FPS to <10 FPS when row count grows from 100 to 1000. So issue is not limited to huge pages.

**how to make sure users can distinguish it from a standard table** 
Virtual Scroll mode (row count is known): everything could be transparent for user (apart from performance); user could not be aware of virtual scrolling.
Infinite Scroll mode (row count is unknown): here user deals with "jumping" scroll slider. Is that problem from UX perspective?

**Comment by ursula-wieshofer** [comment]
Hi @Tomasz-Jasinski 
I understand the use case of showing a lot of log files in a table. What I don't understand is how users are supposed to work with this table - what are they exactly doing, what's their goal? Are they really reading all the hundreds of log lines?
If not, then maybe looking into better filter possibilities would guide the user better than just showing a table with hundreds of entries and solving a performance problem.
What do you think? Any chance you could figure out how users will work with the table?

**Comment by Tomasz-Jasinski** [comment]
Hi @ursula-wieshofer 
Users can inspect logs because of various reasons:
* critical patterns lookup (like exception or error),
* stack trace of exception analysis (may have hundreds of lines),
* performance data analysis (like response time),
* analysis of time correlation of events that have happened.
Hundreds of log lines is not that much if we want to provide some context for the subject that we are looking for. Yes, we will provide table content filtering - as an option.

**Comment by karolinawronska** [comment]
Hi all,

I believe this is the performance issue of this particular component. As long as it harms User Experience, it's not up to us designers to cope with the performance issue of the component, because I personally cannot do anything about performance of the component. What's more - Log Monitoring use cases have to cover 1k+ records on daily.
I'm open for discussion. :) 

Best,
Karolina

**Comment by ffriedl89** [comment]
Hey, I've extended the example for the basic table with 7 columns and 5000 rows. The scroll performance is not significantly slower in my opinion than with less rows. See 
https://stackblitz.com/edit/github-xekfzn?file=src/table/table-default-example/table-default-example.html
Even with 5k rows this is more than acceptable in my opinion. 
Also note that this example runs an online ide next to the iframe with the demo component in it. 

Back to the feature request: 
As I see it since we don't want to have a second scrollbar for the table, but need to connect to a parent scroll container this is not easily achievable on the component level we are on without knowledge about the app that our components are used in. 

I think you can create a virtualized version of the table with what the table already gives you. 
You can specify a placeholder row with another dt-row and a when property. You should be able to set the height on the body element depending on the number of rows to avoid a second scrollbar for the table only. I don't see anything blocking you from creating a proof of concept based on the https://stackblitz.com/edit/cdk-virtual-table-sticky-header-my2ikm?file=src%2Fapp%2Fapp.component.ts with a connection to the body scroll instead of the virtual container events. 

Since this is a very special solution for your usecase, our table already handles a huge amount of rows rather nicely and the solution would be tightly coupled to a scroll container layout of your app, I don't think the component library is the correct place to provide this.

**Comment by Tomasz-Jasinski** [comment]
@ffriedl89 : your example on stackblitz performs ok. However in real life scenario each column usually engages a set of elements (links, spans etc.) and the page contains extra data besides the table.

Regarding the idea of creating virtualized version on my own: probably it's possible. But idea was to make the fix public that other teams (like user session monitoring) would use that.

**Comment by ffriedl89** [comment]
@Tomasz-Jasinski I understand that a reusable approach would be ideal, but given that we don't know the application layout (scroll container) on our level this is really hard to get done on the component level. You still can create a reusable functional version in your app in a shared module/lib that others might use. 

Regarding the performance - I get that a cell might have more content / elements, but the given example has 5 times more cells than what you outlined. So if we would have 1000 rows x 7 columns x 5 elements per cell = 35k elements. 
5000 rows x 7 columns x 1 element per cell = 35k elements. 
I don't see the performance issue on the component level to be honest.

**Comment by Tomasz-Jasinski** [comment]
This request is probably a duplicate - see: https://github.com/angular/components/issues/13862

**Comment by Tomasz-Jasinski** [comment]
There is related bug reported: https://github.com/dynatrace-oss/barista/issues/1141

**Comment by michal-dec** [comment]
@ffriedl89 can we reopen this request and place it in Barista team backlog?

**Comment by tomheller** [comment]
We might be able to look at that when upgrading to angular 12 and the cdk table seems to have some _reusable row rendering_.

**Comment by michal-dec** [comment]
@tomheller any timeline for upgrade to Angular 12?

**Comment by tomheller** [comment]
@michal-dec Currently working on it in the context of APM-321001. Needs some preparation with our build pipeline setup first. But it is definitely on the horizon.
