### ISSUE TITLE
Repository structure in guide for developers is not accurate

### ISSUE THREAD

**Issue by baumgarb** [dynatrace-oss/barista#881]
# Documentation Issue 

The **Repository structure** section of the guide for developers is not accurate / fully correct any more after moving to an Nx Workspace. 

## Expected Behavior

The documentation should reflect and describe what's in the repository.

## Current Behavior

- The folder _components_ does not exist any more on the root level. 
- The folder _libs_ is not documented correctly any more after moving to Nx.
- There are multiple folders under _libs_ (e.g. _examples_, _shared_, _workspace_) which should be named and described for a better understanding.

## Possible Solution

Fix the section **Repository structure** in the guide for developers (DEVELOPMENT.md).

**Comment by baumgarb** [comment]
Note that I'd be happy to fix the documentation. But I'd need some input from you guys:

- What's the libs/workspace folder for? 
- What's the libs/tools compared to the tools folder in root?

If you could give me those answers I'll fix the documentation and I'll create a PR for it. 

Thanks a lot guys!

**Comment by tomheller** [comment]
@lukasholzer could you provide the necessary information to @baumgarb? As you have set up most of these twp folders and probably know the difference better than any of us.

**Comment by lukasholzer** [comment]
Hey, @baumgarb that's nice to hear!

A short explanation of why the structure is like that – codebase grows and there is still a lot of legacy code here.

I want to create a discussion about how we should structure our mono repo because It grew quickly and is currently a little bit of mess due to the lack of time to refactor everything. It is a slow-moving process. 

The `libs/workspace` library is an `nx-plugin` that should contain all the builders, schematics and scripts that are needed to build libraries, create them and run them on the ci. Instead of using the `@nrwl/node:package` builder that is recommended for plugins I use a custom webpack build to bundle it. This enables it that we can import from other libraries and extract shared code.

The  `libs/tools` folder was the older workspace – In the early days of nx, there was nothing introduced like plugins or a way where we can have all the tooling around the library. Originally we had it in the `tools` folder in the workspace root. It contained all the builders, release and everything that is needed for our GitHub actions and our ecosystem. But Nx has some hardcoded constraints so that we had to move the `tools` to the `libs/tools` to leverage the nx listing boundaries. 
This was accomplished in this huge Pull request: #602 where we moved all folders inside the `libs` folder.
One problem originated out of this that of some reasons no `Dockerfiles` and `sh` files where allowed in the libs folder when running `nx workspace-lint`. So we had to leave those libraries outside the libs folder in the `tools` folder.

My plans are now to Restructure the workspace from a component centric point of view – that existed half a year ago where we moved to nx to a more open repository with clear boundaries.

I thought about something like domain-driven design (DDD) for the library to scope the libraries in responsibilities.

For example:

```
apps
- design-system
- angular
-- dev
-- barista-components-e2e
- web-components
-- fluid-components-e2e
-- react-e2e
...
libs
- angular
-- barista-components
--- filter-field
--- ...
-- examples # the angular examples
-- linting
-- testing # angular specific testing stuff
- web-components
-- fluid-components
--- button
--- ...
- design-system
-- barista-content-generation  # design system-related libraries such as the content generation
-- barista-example-generation
-- stackblitz-examples
- workspace # all builders, schematics and scripts
-- release
-- scripts
-- schematics
-- builders
- shared
-- design-tokesn
-- utils # platform-independent shared functionality
```
