### ISSUE TITLE
filter-field: open popup when scrolling down after removing filters

### ISSUE THREAD

**Issue by christian-fischer** [dynatrace-oss/barista#926]
# Bug Report

## Expected Behavior

I think your intended behavior is to not be able to scroll, as long as the filter-field popup is open?

## Current Behavior

When scrolling down, the filter-field popup stays visible in place.

## Steps to Reproduce

Used components: filter-field + table.
The table data source changes depending on the filters.

Example: https://stackblitz.com/edit/github-xnqkhf-lasdrw

1. add a filter
2. remove the filter
3. scroll down

## Context (Environment)

My use case: 
load data from the server depending on the filters in the filter-field; this data is then used for the table data source.

### Used Versions:

- **@dynatrace/barista-components**: 6.3.0

## Attachments

![image](https://user-images.githubusercontent.com/5974170/80580090-48455c80-8a0b-11ea-8def-02a2c9360ebe.png)

**Comment by tomheller** [comment]
Hi @christian-fischer!
Thank you for pointing this out. The dropdown should stay open while the filter field has focus and users should be able to scroll as well to interact with the rest of the page, but the positioning is definitely off. 
We will have a look and see what can be done to fix this.

**Comment by christian-fischer** [comment]
Interesting. I noticed that there is some scrollbar disabling going on, when the popup is open. So this is not intentional?
See example https://stackblitz.com/edit/github-ltwlg3 where I increased the height

**Comment by tomheller** [comment]
I notices as well, this might be a sideeffect of the bug and the positioning of the overlay. 
We are using a cdkOverlay to render the dropdown here, and it might get the wrong positioning logic applied. I haven't had time to check this one yet, but I will keep you posted.

**Comment by christian-fischer** [comment]
Awesome! Thank you @tomheller

**Comment by tomheller** [comment]
After some research, i figured out that apparently the dropdown from the filterfield / autocomplete is currently set to be scrollBlocking.

And it seems that the `scrollStrategies.block()` causes this issue. I'm not quire sure why this is only appearing now.

**Comment by tomheller** [comment]
We have figured it out, thanks to the help of @ffriedl89!
For scroll blocking to work, the body element needs to be expandable (it can't be set to 100vh, which it is in the examples and demo app. Changing the body rule to `min-height: 100vh;`, the scroll blocking works again. 

There is not really something that we can do inside the component level to fix that. If this is an issue in your application and it is breaking, we probably will need to switch the scrollStrategiy of the autocomplete/filterfield overlay to `reposition` instead of `block`.

@christian-fischer Can you confirm, that the css fix on the body fixes your issue?

**Comment by christian-fischer** [comment]
I tried your suggestion, but I cannot confirm that this changes anything. I'm still experiencing the same behaviour, with a style for body with `min-height: 100vh;`

**Comment by tomheller** [comment]
I thought as much. scroll blocking does only work if the body is the scroll container. I guess we are removing the scrollStrategy.block from the autocomplete to fix that.

@christian-fischer The context dialog also uses the blocking strategy. Can you confirm that the scroll blocking is working for these?

@ffriedl89 Any other ideas of fixing this one?

**Comment by christian-fischer** [comment]
@tomheller I'm not using the context-dialog - so I don't know...

**Comment by tomheller** [comment]
Scroll blocking seems to work for the context dialog. This seems to be an issue with the container wrapping the filter field. I'm still not sure if this is an issue on our end. 

Working example of the context dialog with scroll blocking in an overflow container.
https://stackblitz.com/edit/github-a4vqxy?file=src%2Fcontext-dialog%2Fcontext-dialog-default-example%2Fcontext-dialog-default-example.html

**Comment by christian-fischer** [comment]
I think the important part for reproducing this issue is that the data of the table (and subsequently the height of the table) is changing after the popup is already visible. It might be entirely possible that the issue only occurs when using the filter-field in conjunction with the table component.

**Comment by tomheller** [comment]
I was able to reproduce the problem already with the autocomplete component, which is used in the filterfield internally. 
But you make a good point with the height of the overflow container changing after the overlay has been already opened.
After trying this one with the confirmation diolog, it still seems to not be an issue.
https://stackblitz.com/edit/github-a4vqxy?file=src%2Fcontext-dialog%2Fcontext-dialog-default-example%2Fcontext-dialog-default-example.html

**Comment by tomheller** [comment]
After looking into this with @christian-fischer it seems that this might be related to the async updating of the table data (rest call dependent updates).
Scenario:
1. Short list in the table, where the body is not scrollable due to lack of content
2. Scroll strategy evaluates if it is able to block and evaluates to false based on the non overflowing body
3. Rest call finishes and populates the table with more data, extending the body to a scrollable height
4. Result scroll-blocking evaluated to false and the scrollable body can now be scrolled, as blocking is not enabled. 

I will try and recreate a standalone example in stackblitz next.
