### ISSUE TITLE
Bazel: Investigate output Directory.

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#995]
# Feature Request

By default, bazel generates some symlinks while building.

```
- bazel-bin
   - libs/shared/node # built output
- bazel-out
   - darwin-fastbuild
      - bin
         - libs/shared/node # built output
- bazel-testlogs
```

This output structure is not really compatible with migrating bezel seamless in our workspace. Because it would require running every nodejs compiled script with bazel as the location is always different depending on where the bezel build cache is located in the operating system. 

It should be somehow possible to configure this via arguments that can be passed to bazel via the `.bazelrc`. For example https://github.com/ngrx/platform/blob/master/.bazelrc

Investigate a compatible way for the built output.

**Comment by furtnerl** [comment]
It turned out that usually the prefix of the symlinks that Bazel creates is modified via .bazelrc.
Altering the structure of how the build output folder is organized is something that is at best dangerous to do. The tradeoff to adapt all the paths that references the dist/ folder is better than trying to change the fundamental layout of the build system.
